name: Build and deploy ASP.Net Core app to Azure Web App - app-frontend-besportsmart

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APP_NAME: 'app-frontend-besportsmart'
  NODE_VERSION: '20.x'
  DEPLOYMENT_ENVIRONMENT: 'Production'
  VITE_BACKEND_BASE_URL: ${{ vars.BACKEND_BASE_URL }}
  VITE_DYNAMIC_LOCALIZATION_BASE_URL: ${{ vars.DYNAMIC_LOCALIZATION_BASE_URL }}
  VITE_APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ vars.APPLICATIONINSIGHTS_CONNECTION_STRING }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: published-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: ${{ env.DEPLOYMENT_ENVIRONMENT }}
          package: .
          